#mkdocs serve
site_name: Cheyrie
site_url: https://cheyrie.github.io/Nine/
repo_name: Cheyrie
repo_url: https://github.com/Cheyrie/Nine.git
copyright: Cheyrie - Documentation


extra:
  search:
    language: 'zh_CN'
  disqus: 'something'

nav:
- Cheyrie: index.md
- 个人简历: 个人简历.md
- test: test.md




theme:
  name: material
  language: 'zh'
plugins:
  - search:
      indexing: 'full'
extra_javascript:
    - '//busuanzi.ibruce.info//busuanzi/2.3/busuanzi.pure.mini.js'
