#mkdocs serve
site_name: Nine
site_url: https://cheyrie.github.io/Nine/
repo_name: Nine
repo_url: https://github.com/Cheyrie/Nine.git
copyright: Nine - Documentation


extra:
  search:
    language: 'zh_CN'
  disqus: 'something'

nav:
- 家: index.md
- Yum:
  - ius源:
    - iii: 杨春月/ius.md
- 个人简历: 简历.md




theme:
  name: material
  language: 'zh'
plugins:
  - search:
      indexing: 'full'
extra_javascript:
    - '//busuanzi.ibruce.info//busuanzi/2.3/busuanzi.pure.mini.js'
